export { default as Skeleton } from './Skeleton.svelte'
export { default as SkeletonAvatar } from './SkeletonAvatar.svelte'
export { default as SkeletonImage } from './SkeletonImage.svelte'
export { default as SkeletonParagraph } from './SkeletonParagraph.svelte'
export { default as SkeletonTitle } from './SkeletonTitle.svelte'
